### ISSUE TITLE
Resolve $refs

### ISSUE THREAD

**Issue by ioggstream** [koxudaxi/fastapi-code-generator#15]
## I expect

the generator to resolve refs

## Instead

It doesn't

**Comment by koxudaxi** [comment]
@ioggstream 
Thank you for creating this issue.
> the generator to resolve refs

What type refs do you want to resolve?
Currently, the generator returns only last one element which is split `/`
https://swagger.io/docs/specification/using-ref/

Other local file? or remote file?

**Comment by ioggstream** [comment]
Today I'll PR more breaking test cases and will look for a solution.

I expect all refs to be resolved, but let's do it incrementally :)

**Comment by ioggstream** [comment]
related to https://github.com/koxudaxi/datamodel-code-generator/issues/156

**Comment by koxudaxi** [comment]
I believe the problem is resolved.
