### ISSUE TITLE
How to update api.yaml and keep main.py route logic?

### ISSUE THREAD

**Issue by ddehueck** [koxudaxi/fastapi-code-generator#181]
1. Let's say I currently have the api.yaml and added route logic to main.py (no longer just "pass"):

```python
# generated by fastapi-codegen:
#   filename:  api.yaml
#   timestamp: 2020-06-14T10:45:22+00:00

from __future__ import annotations

from typing import Optional

from fastapi import FastAPI, Query

from .models import Pets

app = FastAPI(version="1.0.0", title="Swagger Petstore", license="{'name': 'MIT'}",)


@app.get('/pets', response_model=Pets)
def list_pets(limit: Optional[int] = None) -> Pets:
    """
    List all pets
    """
    # Added logic
    return db.pets.get().limit(limit)
```

2. I now realize I want to add another search parameter `offset` so I make the necessary changes in api.yaml and run `fastapi-codegen --input api.yaml --output app`

**The output I receive:**
```python
@app.get('/pets', response_model=Pets)
def list_pets(limit: Optional[int] = None, offset: Optional[int] = None) -> Pets:
    """
    List all pets
    """
    pass
```

**Versus the output I would like:**
```python
@app.get('/pets', response_model=Pets)
def list_pets(limit: Optional[int] = None, offset: Optional[int] = None) -> Pets:
    """
    List all pets
    """
    # Added logic
    return db.pets.get().limit(limit)
```

Is it possible to get this behavior?

**Comment by koxudaxi** [comment]
@ddehueck 
Thank you for creating this issue.
if you know the rule then you can resolve the problem by the custom template option ` -t, --template-dir`

Example template:
https://github.com/koxudaxi/fastapi-code-generator/tree/master/tests/data/custom_template/security

**Comment by ddehueck** [comment]
Hi @koxudaxi thanks for the response! I do see I can update the template and add code that will always be a part of the template but I don't think that's quite what I'm looking for.

The rule I have in mind would be: if operation already exists in` main.py` keep route logic (don't replace with `pass`) but rebuild function definition. This ways it's easy to add new paths and parameters to an existing file.

**Comment by olivergondza** [comment]
I run into the same problem. Oftentimes, the schema is a living thing that we want to evolve, and code generation is a great way to keep the code and schema in sync.

**Comment by rumblefrog** [comment]
Stumbled across this. If possible, could the routing be a parent class, and the implementation/consumer can inherit the class and add the implementation?

This way, the parent/stub classes can be regenerated without overwriting things.
