### ISSUE TITLE
Add support for tags

### ISSUE THREAD

**Issue by rominf** [koxudaxi/fastapi-code-generator#207]
It would be great to have support for tags. I volunteer to implement this, I just don't want to start implementing it before https://github.com/koxudaxi/fastapi-code-generator/pull/203 is merged to avoid merge conflicts.

FastAPI docs: https://fastapi.tiangolo.com/tutorial/path-operation-configuration/#tags

**Comment by n0nvme** [comment]
Looks like it's already implemented. You can use `operation.tags` variable in your custom template.

**Comment by koxudaxi** [comment]
Yes, we should add tag in default output

**Comment by koxudaxi** [comment]
@n0nvme  @rominf 
I have released the feature as `0.4.0` 
Thank you very much!!
