### ISSUE TITLE
Support 'application/foobar+json'

### ISSUE THREAD

**Issue by ioggstream** [koxudaxi/fastapi-code-generator#25]
## I expect

`application/foobar+json` to be supported, eg  `application/problem+json`

## Instead

They are not parsed

## See

parser.py:242

**Comment by koxudaxi** [comment]
Thank you for suggesting the issue.
OK, We will support it.

**Comment by ioggstream** [comment]
I'll PR on that this week.

**Comment by koxudaxi** [comment]
@ioggstream
I have released a new version as 0.0.16

**Comment by ioggstream** [comment]
Thanks @koxudaxi ! Great work!!!!

**Comment by ioggstream** [comment]
I'm closing... if something breaks, we'll reopen.
