### ISSUE TITLE
Outdated datamodel-codegen version in PyPI/last release

### ISSUE THREAD

**Issue by aktentasche** [koxudaxi/fastapi-code-generator#281]
Hi,

I am using datamodel-code-generator as well as fastapi-code-generator in a project (thanks for your efforts!)

Unfortunately datamodel-code-generator is currently pinned at 0.11.19 in the PyPI at the last release 0.3.5 and I would like to use the newest, fancy features of datamodel-code-generator ;)

Would it be possible to create a new release with datamodel-code-generator  0.13.1 (that's the current master branch version)?

Cheers
Jonas

**Comment by aktentasche** [comment]
P.S.: in the mean time I will use 

`poetry add git+https://github.com/koxudaxi/fastapi-code-generator.git#master`

**Comment by aktentasche** [comment]
Awesome, thanks :rocket:

**Comment by koxudaxi** [comment]
@aktentasche 
Thank you for your sponsoring :bow:
