### ISSUE TITLE
Request: Rest API clients generator.

### ISSUE THREAD

**Issue by OmarAlJarrah** [koxudaxi/fastapi-code-generator#320]
Dear Koudai Aono San,
I have been interested in your work recently, especially the two projects:

1. [fastapi-code-generator](https://github.com/koxudaxi/fastapi-code-generator).
2. [datamodel-code-generator](https://github.com/koxudaxi/datamodel-code-generator).

I have started working on a new project built on top of these two projects, the new project's goal is to generate REST API SDKs. I found that [fastapi-code-generator](https://github.com/koxudaxi/fastapi-code-generator) already has a good base to build this project on top of, though it lacks few abilities to fully support that, it should not be a problem.

I would like to contribute to both [fastapi-code-generator](https://github.com/koxudaxi/fastapi-code-generator) and [datamodel-code-generator](https://github.com/koxudaxi/datamodel-code-generator), while using them as a base to support the new project (REST API SDK generator), and I would like to hear your thoughts on the idea, maybe you can start a new repository under your profile if you like the idea.

Thank you for being a great open-source developer.

**Comment by koxudaxi** [comment]
@OmarAlJarrah 
Thank you for creating the issue.
I have experienced thinking about the project.
https://github.com/koxudaxi/fastapi-code-generator/issues/95
https://github.com/koxudaxi/datamodel-code-generator/issues/40

I understand we need a robust API client generated from OpenAPI.
However, I didn't have a good idea of the best client.
for example, class base vs function base?

Do you have an idea of what will be a good starting point?

**Comment by OmarAlJarrah** [comment]
@koxudaxi 
Thank for taking interest in the idea.

In order to get to the most optimal client, it needs more thinking about the requirements users would demand, but if I think about it really quick, few points to mention are:

- Class base vs Function base: I would go for a class base client, as it would give us more flexibility and extensibility, and would make it a bit easier for users to extend/override as they desire.
- Dependency Injection: I would think about having dependency injection, while having few interfaces (or ABCs), in case users prefer to have their own implementation of any component of the platform as a whole (`AuthenticationClient` for example).
- `sync` vs `async`: I think we will need to support both, but as `sync` is the most popular in the community (or so I believe), it should be the starting point.
- API vs CLI: I would go for supporting both, I have seen that in [fastapi-code-generator](https://github.com/koxudaxi/fastapi-code-generator), there is no API which supports generating through a programmatical solution, but rather I had to override the `OpenApiParser` by having a new class inheriting from it, and then copying and pasting both `main()` and `generate()` methods, which I would have loved if there was a programmatical API in which it can make my life easier.

These are the first few ideas which come to me, what is your opinion on that?

Thank you for your cooperation, Koudai Aono San!
^^

**Comment by koxudaxi** [comment]
@OmarAlJarrah 
I agree with you.

I thought about the topic last weekend.
you know users have a bunch of use cases for their projects.
We will get many feature requests from users near future.
We should have many options and customization after creating prototypes.
It means concrete implementation is not important. I'm sorry I asked you the question 😅   But, I'm happy to hear your options.

There are some client code generators such as https://github.com/OpenAPITools/openapi-generator/tree/0cf5ed619dbe61058a1ea4cdc68fe2be42777757/samples/openapi3/client/petstore/python-nextgen-aiohttp or https://github.com/dmontagu/fastapi_client
We should define the concept before starting implementation. 
-  Can be used as CLI, python module
- Provide options (exp: `sync or async`, `class or function style`)
- Support custom Jinja template
- Dependency Injection
- Production Ready (exp: the generated client has logger feature)

Do you have another concept?
