### ISSUE TITLE
Not able to generate Fast API code from Open API yaml file

### ISSUE THREAD

**Issue by sagu94271** [koxudaxi/fastapi-code-generator#38]
I am getting below error while running the command to generate the code : fastapi-codegen --input openapi.yaml --output app

TypeError: _evaluate() missing 1 required positional argument: 'recursive_guard'

![image](https://user-images.githubusercontent.com/38607315/97409472-f15b0a00-18fd-11eb-9e2d-479dc83d42bc.png)

**Comment by koxudaxi** [comment]
Thank you for creating the issue.
The problem may come from Python 3.9.
Older pydantic don't support Python3.9.
I will fix the problem.

**Comment by ioggstream** [comment]
@sagu94271 can you pls rename the issue with a more precise title? :) Thanks++, R.

**Comment by koxudaxi** [comment]
@sagu94271 
I have released a new version as `0.0.17`
This version supports Python3.9
