### ISSUE TITLE
[suggestion] Explicitly stating the required python version

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [koxudaxi/fastapi-code-generator#43]
I tried to install this library for quite a while, but pip couldn't find an appropriate version which confused me quite a lot. After a while, I realized I had python 3.7 and maybe that was the issue. After seeing the badge with python 3.8, I realized I had to use 3.8 and it worked. However, this requirement is not explicitly stated anywhere as far as I could find, apart from the button. 

I think it would be clearer if this was added somewhere for clarity. I also don't know if the 3.8 is a hard requirement or that is only has been tested for that version, but I'll leave that open.

**Comment by koxudaxi** [comment]
Thank you for posting the suggestion.

OK, I will define the required version or change the minimum required version.

I keep opening this issue for getting any opinion.

**Comment by koxudaxi** [comment]
@Baukebrenninkmeijer 
I have released a new version as `0.0.17`
This version supports Python3.7

**Comment by Baukebrenninkmeijer** [comment]
@koxudaxi Great, thanks!
