### ISSUE TITLE
Schema with enums optional fields are not generated correctly

### ISSUE THREAD

**Issue by boaza** [koxudaxi/fastapi-code-generator#64]
When the schema includes optional string properties with enum format, the generated model crashes with the following exception:
`TypeError: Optional[t] requires a single type. Got FieldInfo(description='', extra={}).`

The reason is the generated Enum class has the same name as the Field:
    from enum import Enum
    from typing import Optional
    
    from pydantic import BaseModel, Field
    
    class Prop(Enum):
        A = 'A'
        B = 'B'
        C = 'C'
    
    class Request(BaseModel):
        Prop: Optional[Prop] = Field(None, description='') # <-- the problem is here`

When run, `Optional.__getitem__()`' gets `Prop` - the `FieldInfo`, not the `Enum` class. Changing `class Prop(Enum)` to `class PropEnum(Enum)` solved the probelm.

To reproduce, run with the following schema:
    `openapi: 3.0.0
    servers:
      - description: SwaggerHub API Auto Mocking
        url: 'https://virtserver.swaggerhub.com/cropmodel/1.0.0'
    info:
      description: Demo
      version: 1.0.0
      title: Demo
    paths:
      /:
        post:
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Request'
          responses:
            '200':
              description: OK
            '400':
              description: bad input parameter
    components:
      schemas:
        Request:
          type: object
          properties:
            Prop:
              type: string
              enum: [A, B, C]
              description: ""`

**Comment by boaza** [comment]
Found the root cause:
In Python 3.7 the generated models.py file is missing an import:
`from __future__ import annotations`

Generating directly from datamodel-code-generator (or adding the missing import) resolves the issue.

**Comment by koxudaxi** [comment]
Thank you for creating this issue.
OK, I will fix it in`datamodel-code-generator `

**Comment by koxudaxi** [comment]
@boaza 
I fixed it and relased a new version as `0.0.19`
